//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetBase.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNetBase.Resources.IdentityStrings", typeof(IdentityStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما مسدود شده است..
        /// </summary>
        public static string Err_Login_Blocked {
            get {
                return ResourceManager.GetString("Err_Login_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا کلمه عبور وارد شده نادرست می باشند..
        /// </summary>
        public static string Err_Login_Invalid {
            get {
                return ResourceManager.GetString("Err_Login_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود دو مرحله ای برای حساب کاربری شما الزامی است..
        /// </summary>
        public static string Err_Login_RequireTwoFactor {
            get {
                return ResourceManager.GetString("Err_Login_RequireTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت کاربری شما برای ورود نامعتبر است..
        /// </summary>
        public static string Err_Login_StatusInvalid {
            get {
                return ResourceManager.GetString("Err_Login_StatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود با موفقیت انجام شد.
        /// </summary>
        public static string Ok_Login {
            get {
                return ResourceManager.GetString("Ok_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً کلمه عبور خود را وارد نمایید..
        /// </summary>
        public static string Req_Login_Password {
            get {
                return ResourceManager.GetString("Req_Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً نام کاربری خود را وارد نمایید..
        /// </summary>
        public static string Req_Login_UserName {
            get {
                return ResourceManager.GetString("Req_Login_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربر را وارد کنید.
        /// </summary>
        public static string Req_User_FirstName {
            get {
                return ResourceManager.GetString("Req_User_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی کاربر را وارد کنید.
        /// </summary>
        public static string Req_User_LastName {
            get {
                return ResourceManager.GetString("Req_User_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی کاربر را وارد نمایید..
        /// </summary>
        public static string Req_User_NationalCode {
            get {
                return ResourceManager.GetString("Req_User_NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری را وارد کنید..
        /// </summary>
        public static string Req_User_UserName {
            get {
                return ResourceManager.GetString("Req_User_UserName", resourceCulture);
            }
        }
    }
}
